# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties (Minecraft 1.21.8)
# check https://fabricmc.net/develop
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.19.3

# Fabric API
fabric_version=0.136.1+1.21.8

# Mod Properties
mod_version=1.0.0
maven_group=com.autominer
archives_base_name=worldutils
